# name属性用来指定这个工作流的名字
name: weixin-push-weater

# 这个部分用来指定能够触发工作流执行的事件
on:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
  push:
    branches: [main]
  schedule:
    cron: "0 9 * * *"

# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:
      # 首先copy git仓库到虚拟机上
      - name: Checkout
        uses:
          actions/checkout@v2
          # 安装初始化python
      - name: Setup Node.js
        uses: actions/setup-node@v2 #安装node.js
        with:
          node-version: "14"

      - name: Install Dependency
        run: |
          npm install
      - name: Working
        env:
          SCKEY: ${{ secrets.SCKEY }}
          SKEY: ${{ secrets.SKEY }}
        run: node ./weather.js
